### ISSUE TITLE
Can we connect tg bot instead of tg channel to get results from?

### ISSUE THREAD

**Issue by askfriends** [kevinnadar22/T2linksMovie#1]
HI;
currently it seems like data is being fetched from a tg channel, which is good in a way but i want to know can we fetch data from tg bot instead of tg channel?

For eg, i have a yt music video search bot which searches videos from youtube with a command /search and display the results in in response in buttons, when user click on his choice the bot displays the url or opens that url in browser, So can we do the same via website? so that search button on website will act as /search command to the bot, and website will show the results fetched from tg bot, and if user click on any button it will show the url.

I hope you get my point. thanks

**Comment by kevinnadar22** [comment]
Hey, 

The bot fetches the data from a static json file exported from mongodb, this project was made for practice and hence not maintained. [Json File](https://gist.githubusercontent.com/kevinnadar22/112e759f1f6f7747c5df8d8749e464f0/raw/0190049fe65baabc057662495125b0070cb6d764/data.json)

You can fork the repo and make the necessary changes or refer to this [repo](https://github.com/odysseusmax/tg-index) which indexes your telegram account to website using session string. This is the repo you maybe looking for
